# French translations for INSECA package.
# Copyright (C) 2022 THE INSECA'S COPYRIGHT HOLDER
# This file is distributed under the same license as the INSECA package.
# Automatically generated, 2022.
# Vivien Malerba <vmalerba@gmail.com>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: INSECA 2\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-07-11 19:35+0200\n"
"PO-Revision-Date: 2022-01-30 14:30+0100\n"
"Last-Translator: Vivien Malerba <vmalerba@gmail.com>\n"
"Language-Team: français <vmalerba@gmail.com>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"X-Generator: Gtranslator 3.30.1\n"

#: ../lib/AppendedData.py:40 ../lib/AppendedData.py:42
#, python-format
msgid "Could not find reference '%s'"
msgstr "Impossible de trouver la référence '%s'"

#: ../lib/AppendedData.py:74
msgid "In creation mode, both specs and layout are expected"
msgstr ""

#: ../lib/AppendedData.py:81
#, python-brace-format
msgid "Device file mismatch: '{devfile}' specified and '{layout}' in layout"
msgstr ""

#: ../lib/AppendedData.py:105
#, python-format
msgid "Unknown partitioning type '%s'"
msgstr ""

#: ../lib/AppendedData.py:115
#, python-brace-format
msgid ""
"Not enough reserved space on device (got {offset} out of {reserved} reserved)"
msgstr ""

#: ../lib/AppendedData.py:121
msgid "Actual metadata has not yet been created or read from the device"
msgstr ""

#: ../lib/AppendedData.py:128
msgid "Not enough reserved space for metadata's length"
msgstr ""

#: ../lib/AppendedData.py:167
msgid "Absent or invalid device signature"
msgstr ""

#: ../lib/AppendedData.py:183
msgid "Can't create metadata in non creation mode"
msgstr ""

#: ../lib/AppendedData.py:262 ../lib/AppendedData.py:331
msgid "Actual metadata has been read from the device"
msgstr ""

#: ../lib/AppendedData.py:264
msgid "No metadata verifiers provided"
msgstr ""

#: ../lib/AppendedData.py:279
msgid ""
"No matching signature verifer: metadata's signature could not be verified"
msgstr ""

#: ../lib/AppendedData.py:288
msgid "H/W model mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:294
msgid "Serial numbers mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:298
msgid "Device size mismatch: wrong device"
msgstr ""

#: ../lib/AppendedData.py:304
#, python-brace-format
msgid "Partition label scheme has been altered from '{etype}' to '{gtype}'"
msgstr ""

#: ../lib/AppendedData.py:308
msgid "Partition table has been altered"
msgstr ""

#: ../lib/AppendedData.py:318
#, python-brace-format
msgid ""
"Filesystem for partition {number} has been modified from '{fs}' to '{fstype}'"
msgstr ""

#: ../lib/AppendedData.py:323
#, python-format
msgid "Partition %d has been altered"
msgstr ""

#: ../lib/AppendedData.py:327
#, python-format
msgid "Files in partition %d have changed"
msgstr ""

#: ../lib/AppendedData.py:346
msgid "Can't create security data in non creation mode"
msgstr ""

#: ../lib/Borg.py:93
msgid "Incomplete synchronisation, retry later"
msgstr ""

#: ../lib/Borg.py:95
msgid "Not enough memory(?)"
msgstr ""

#: ../lib/Borg.py:115
#, fuzzy
msgid "Could not initialize repository"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:135
#, fuzzy
msgid "Could not create archive"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:151
#, fuzzy
msgid "Failed to get archives list"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:166
msgid "Repository is being modified, try again later"
msgstr ""

#: ../lib/Borg.py:186
#, fuzzy
msgid "Could not list archives"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:195
msgid "Archive to extract is not specified"
msgstr ""

#: ../lib/Borg.py:197
#, python-format
msgid "Destination path '%s' does not exist"
msgstr ""

#: ../lib/Borg.py:199
#, python-format
msgid "Destination path '%s' is not a directory"
msgstr ""

#: ../lib/Borg.py:204
#, fuzzy
msgid "Could not extract archive"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:211
#, fuzzy
msgid "Could not list files in archive"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:215
#, fuzzy
msgid "Could not delete archive"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:231
#, fuzzy, python-format
msgid "Could not mount archive '%s'"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:234
#, python-brace-format
msgid "Mounted archive '{archive_name}' on '{mp}'"
msgstr ""

#: ../lib/Borg.py:259
#, python-format
msgid "Could not umount archive '%s': timed out"
msgstr ""

#: ../lib/Borg.py:263
#, fuzzy, python-format
msgid "Could not umount archive '%s'"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/Borg.py:271
#, python-brace-format
msgid "Unmounted archive '{archive_name}' (was mounted on '{mp}')"
msgstr ""

#: ../lib/Configurations.py:54 ../lib/Configurations.py:71
#, python-format
msgid "Missing attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:58
#, python-format
msgid "Invalid attribute '%s': should not be null"
msgstr ""

#: ../lib/Configurations.py:60
#, python-format
msgid "Invalid attribute '%s': wrong data type"
msgstr ""

#: ../lib/Configurations.py:64
#, python-format
msgid "Expected a dictionary, got: %s"
msgstr ""

#: ../lib/Configurations.py:68
#, python-format
msgid "Invalid attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:74
msgid "Invalid 'descr' attribute: wrong type"
msgstr ""

#: ../lib/Configurations.py:76
#, python-format
msgid "Invalid 'type' attribute '%s'"
msgstr ""

#: ../lib/Configurations.py:78
msgid "Invalid 'attest' attribute: wrong type"
msgstr ""

#: ../lib/Configurations.py:84
#, python-format
msgid "Wrong value '%s' for a string parameter"
msgstr ""

#: ../lib/Configurations.py:91
#, python-format
msgid "Missing file '%s' identified in parameter"
msgstr ""

#: ../lib/Configurations.py:94
#, python-format
msgid "Wrong value '%s' for parameter"
msgstr ""

#: ../lib/Configurations.py:99
#, python-format
msgid "Wrong value '%s' for a filesystem parameter"
msgstr ""

#: ../lib/Configurations.py:142 ../lib/Configurations.py:380
#: ../lib/Configurations.py:564 ../lib/Configurations.py:702
#: ../lib/Configurations.py:773
#, python-brace-format
msgid "Invalid file '{configfile}' format: {err}"
msgstr ""

#: ../lib/Configurations.py:203
#, python-format
msgid "Missing live Linux signing private key file '%s'"
msgstr ""

#: ../lib/Configurations.py:215
#, python-format
msgid "Missing live Linux signing public key file '%s'"
msgstr ""

#: ../lib/Configurations.py:353
#, python-format
msgid ""
"Build configuration is not 'workstation' but included component '%s' "
"requires some USERDATA"
msgstr ""

#: ../lib/Configurations.py:494
#, python-brace-format
msgid "Invalid install configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:519 ../lib/Configurations.py:664
#, python-format
msgid "Invalid parameter '%s': already part of core configuration"
msgstr ""

#: ../lib/Configurations.py:529 ../lib/Configurations.py:674
#, python-brace-format
msgid ""
"Invalid configuration entry '{entry}' in section '{section}': already part "
"of core configuration"
msgstr ""

#: ../lib/Configurations.py:540
msgid "Build configuration is not of type 'workstation'"
msgstr ""

#: ../lib/Configurations.py:641
#, python-brace-format
msgid "Invalid format configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:818
#, python-brace-format
msgid "Could not get actual size of '{self.path}': {err}"
msgstr ""

#: ../lib/Configurations.py:844
msgid "Invalid configuration: not a dictionary"
msgstr ""

#: ../lib/Configurations.py:858
#, python-brace-format
msgid "Invalid repo configuration '{config_file}': {err}"
msgstr ""

#: ../lib/Configurations.py:863
#, python-brace-format
msgid ""
"Invalid repo configuration '{config_file}': path '{path}' does not exist"
msgstr ""

#: ../lib/Configurations.py:868
#, python-brace-format
msgid "Invalid repo configuration '{config_file}': invalid type '{self._type}'"
msgstr ""

#: ../lib/Configurations.py:986
#, python-format
msgid "Root directory '%s' is not empty"
msgstr ""

#: ../lib/Configurations.py:1007
msgid "INSECA_ROOT environment variable is not defined"
msgstr ""

#: ../lib/Configurations.py:1010
#, python-format
msgid ""
"Directory '%s' pointed by INSECA_ROOT environment variable does not exist"
msgstr ""

#: ../lib/Configurations.py:1017
#, python-format
msgid "Top directory '%s' is missing"
msgstr ""

#: ../lib/Configurations.py:1019
#, python-format
msgid "'%s' should be a directory"
msgstr ""

#: ../lib/Configurations.py:1066
msgid "The archives_cache_dir property has not yet been defined"
msgstr ""

#: ../lib/Configurations.py:1108
#, python-format
msgid "Global configuration file '%s' is missing"
msgstr ""

#: ../lib/Configurations.py:1127
#, python-brace-format
msgid "'reader-conf' file '{fname}' not found for entry '{entry}'"
msgstr ""

#: ../lib/Configurations.py:1134
#, python-brace-format
msgid "'writer-conf' file '{fname}' not found for entry '{entry}'"
msgstr ""

#: ../lib/Configurations.py:1172
#, python-format
msgid "Unknown synchronization target '%s'"
msgstr ""

#: ../lib/Configurations.py:1217
#, python-brace-format
msgid "Build configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1237 ../lib/Configurations.py:1272
#, python-brace-format
msgid "Install configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1252
#, python-format
msgid "Missing format configuration file '%s'"
msgstr ""

#: ../lib/Configurations.py:1256
#, python-brace-format
msgid "Format configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1296
#, python-brace-format
msgid "Repository configuration '{conf.id}' already exists (from '{path}')"
msgstr ""

#: ../lib/Configurations.py:1312
#, python-brace-format
msgid ""
"Install configuration '' references inexistant build ID '{iconf.build_id}'"
msgstr ""

#: ../lib/Configurations.py:1316
#, python-brace-format
msgid ""
"Install configuration '{path}' references live Linux build configuration "
"which has no associated repository"
msgstr ""

#: ../lib/Configurations.py:1320
#, python-brace-format
msgid ""
"Install configuration '{path}' references inexistant build repository 'iconf."
"build_repo_id'"
msgstr ""

#: ../lib/Configurations.py:1324
#, python-brace-format
msgid ""
"Install configuration '{path}' references build repo ID '{iconf."
"build_repo_id}' which is not of type BUILD"
msgstr ""

#: ../lib/Configurations.py:1329
#, python-brace-format
msgid ""
"Install configuration '{path}' references inexistant repo ID '{iconf."
"repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1332
#, python-format
msgid ""
"Install configuration '%s' references repo ID which is not of type INSTALL"
msgstr ""

#: ../lib/Configurations.py:1341
#, python-brace-format
msgid ""
"Format configuration '{path}' references inexistant repo ID '{fconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1344
#, python-format
msgid ""
"Format configuration '%s' references repo ID which is not of type FORMAT"
msgstr ""

#: ../lib/Configurations.py:1353
#, python-brace-format
msgid ""
"Build configuration '{path}' references inexistant repo ID '{bconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1356
#, python-format
msgid "Build configuration '%s' references repo ID which is not of type BUILD"
msgstr ""

#: ../lib/Configurations.py:1364
#, python-brace-format
msgid ""
"Domain configuration '{path}' references inexistant repo ID '{dconf.repo_id}'"
msgstr ""

#: ../lib/Configurations.py:1368
#, python-brace-format
msgid ""
"Domain configuration '{path}' references domain repo ID '{dconf.repo_id}' "
"which is not of type DOMAIN"
msgstr ""

#: ../lib/Configurations.py:1371
#, python-format
msgid ""
"Invalid 'install-ref' part in domain configuration: references unknown "
"install configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1396 ../lib/Configurations.py:1426
#: ../lib/Configurations.py:1456 ../lib/Configurations.py:1486
msgid "More than one matching configuration"
msgstr ""

#: ../lib/Configurations.py:1403
#, python-format
msgid "Unknown build configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1433
#, python-format
msgid "Unknown install configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1463
#, python-format
msgid "Unknown format configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1493
#, python-format
msgid "Unknown domain configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1511
#, python-format
msgid "Unknown repo configuration '%s'"
msgstr ""

#: ../lib/Configurations.py:1529
msgid "No build archive available"
msgstr ""

#: ../lib/Configurations.py:1532 ../lib/Configurations.py:1560
#, python-format
msgid "No archive '%s' in repository"
msgstr ""

#: ../lib/Configurations.py:1540
#, python-brace-format
msgid ""
"Build repo '{rconf.id}' seems corrupted: missing the '{file_iso}' file in "
"archive '{barname}'"
msgstr ""

#: ../lib/Configurations.py:1544
#, python-brace-format
msgid ""
"Build repo '{rconf.id}' seems corrupted: missing the '{file_userdata}' file "
"in archive '{barname}'"
msgstr ""

#: ../lib/Configurations.py:1548
#, python-brace-format
msgid ""
"Build repo '{rconf.id}' seems corrupted: missing the '{file_infos}' file in "
"archive '{barname}'"
msgstr ""

#: ../lib/Configurations.py:1592
msgid ""
"Archives cache directory cannot be a subdirectory of the configuration's "
"global directory"
msgstr ""

#: ../lib/CryptoGen.py:38
#, python-format
msgid "Password is too short (%d characters)"
msgstr ""

#: ../lib/CryptoGen.py:42
#, python-format
msgid "Alphabet to generate password from is too small: %d long"
msgstr ""

#: ../lib/CryptoGen.py:51
#, python-format
msgid "Invalid character '%s'"
msgstr ""

#: ../lib/CryptoGen.py:54 ../lib/CryptoPass.py:63
msgid "Invalid password: not strong enough"
msgstr ""

#: ../lib/CryptoGen.py:165
msgid "Invalid data: can't convert from ascii"
msgstr ""

#: ../lib/CryptoPass.py:61
msgid "Invalid password: expected a string"
msgstr ""

#: ../lib/CryptoPass.py:77
#, python-format
msgid "Could not encrypt data with password: %s"
msgstr ""

#: ../lib/CryptoPass.py:91 ../lib/CryptoX509.py:131
#, python-format
msgid "Invalid format for data to decrypt '%s'"
msgstr ""

#: ../lib/CryptoPass.py:99
#, python-format
msgid "Could not decrypt data using password: %s"
msgstr ""

#: ../lib/CryptoPass.py:130
msgid "Could not verify the signature"
msgstr ""

#: ../lib/CryptoX509.py:37
#, python-format
msgid "Could not generate a new private RSA key: %s"
msgstr ""

#: ../lib/CryptoX509.py:41
#, python-format
msgid "Could not generate a new public RSA key: %s"
msgstr ""

#: ../lib/CryptoX509.py:49
#, python-format
msgid "Could not extract public key from certificate: %s"
msgstr ""

#: ../lib/CryptoX509.py:54
msgid "Could not determine public key type of certificate"
msgstr ""

#: ../lib/CryptoX509.py:67
#, python-brace-format
msgid "Could not sign file '{data_file}': {err}"
msgstr ""

#: ../lib/CryptoX509.py:79
#, python-brace-format
msgid "Signature verification failed for file '{data_file}': {err}"
msgstr ""

#: ../lib/CryptoX509.py:92
msgid "No public key provided, can't encrypt"
msgstr ""

#: ../lib/CryptoX509.py:107
#, python-format
msgid "Could not encrypt symetric key with certificate's public key: %s"
msgstr ""

#: ../lib/CryptoX509.py:114
#, python-format
msgid "Could not encrypt data with symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:143
#, python-format
msgid "Could not decrypt intermediate symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:151
#, python-format
msgid "Could not decrypt data using symetric key: %s"
msgstr ""

#: ../lib/CryptoX509.py:162
msgid "No private key provided, can't sign"
msgstr ""

#: ../lib/CryptoX509.py:174
#, fuzzy, python-format
msgid "Could not create signature: %s"
msgstr "Impossible de lister les archives '%s'"

#: ../lib/CryptoX509.py:189
msgid "No public key provided, can't verify signature"
msgstr ""

#: ../lib/CryptoX509.py:198
msgid "Invalid signature format"
msgstr ""

#: ../lib/CryptoX509.py:212
#, python-format
msgid "Unable to verify signature: %s"
msgstr ""
